name: Build Windows App

on:
  push:
    branches:
      - main
      - qa
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: pnpm install

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: apps/web

      - name: Rename Installer
        shell: bash
        run: |
          mv apps/web/src-tauri/target/release/bundle/msi/*.msi apps/web/src-tauri/target/release/bundle/msi/MerxPOS-Installer.msi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Release
          files: apps/web/src-tauri/target/release/bundle/msi/MerxPOS-Installer.msi
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
